"""change editedBy & createdBy data type

Revision ID: 5a0bb7a98cb7
Revises: e62c9f8b00a0
Create Date: 2022-10-10 20:38:26.136194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a0bb7a98cb7'
down_revision = 'e62c9f8b00a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('choice', sa.Column('createdBy', sa.Integer(), nullable=True))
    op.add_column('choice', sa.Column('editedBy', sa.Integer(), nullable=True))
    op.add_column('question', sa.Column('createdBy', sa.Integer(), nullable=True))
    op.add_column('question', sa.Column('editedBy', sa.Integer(), nullable=True))
    op.add_column('quiz', sa.Column('createdBy', sa.Integer(), nullable=True))
    op.add_column('quiz', sa.Column('editedBy', sa.Integer(), nullable=True))
    op.add_column('record_answer', sa.Column('createdBy', sa.Integer(), nullable=True))
    op.add_column('record_answer', sa.Column('editedBy', sa.Integer(), nullable=True))
    op.add_column('record_quiz', sa.Column('createdBy', sa.Integer(), nullable=True))
    op.add_column('record_quiz', sa.Column('editedBy', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('createdBy', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('editedBy', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'editedBy')
    op.drop_column('user', 'createdBy')
    op.drop_column('record_quiz', 'editedBy')
    op.drop_column('record_quiz', 'createdBy')
    op.drop_column('record_answer', 'editedBy')
    op.drop_column('record_answer', 'createdBy')
    op.drop_column('quiz', 'editedBy')
    op.drop_column('quiz', 'createdBy')
    op.drop_column('question', 'editedBy')
    op.drop_column('question', 'createdBy')
    op.drop_column('choice', 'editedBy')
    op.drop_column('choice', 'createdBy')
    # ### end Alembic commands ###
