"""first init

Revision ID: ca3ce40ef130
Revises: 
Create Date: 2022-10-10 15:30:06.667184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca3ce40ef130'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record_quiz', sa.Column('pengerja_id', sa.Integer(), nullable=True))
    op.drop_constraint('record_quiz_user_id_fkey', 'record_quiz', type_='foreignkey')
    op.create_foreign_key(None, 'record_quiz', 'user', ['pengerja_id'], ['id'])
    op.drop_column('record_quiz', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record_quiz', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'record_quiz', type_='foreignkey')
    op.create_foreign_key('record_quiz_user_id_fkey', 'record_quiz', 'user', ['user_id'], ['id'])
    op.drop_column('record_quiz', 'pengerja_id')
    # ### end Alembic commands ###
