"""remove editedBy & createdBy

Revision ID: e62c9f8b00a0
Revises: ca3ce40ef130
Create Date: 2022-10-10 20:37:35.970609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e62c9f8b00a0'
down_revision = 'ca3ce40ef130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('choice', 'createdBy')
    op.drop_column('choice', 'editedBy')
    op.drop_column('question', 'createdBy')
    op.drop_column('question', 'editedBy')
    op.drop_column('quiz', 'createdBy')
    op.drop_column('quiz', 'editedBy')
    op.drop_column('record_answer', 'createdBy')
    op.drop_column('record_answer', 'editedBy')
    op.drop_column('record_quiz', 'createdBy')
    op.drop_column('record_quiz', 'editedBy')
    op.drop_column('user', 'createdBy')
    op.drop_column('user', 'editedBy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('editedBy', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('createdBy', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('record_quiz', sa.Column('editedBy', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('record_quiz', sa.Column('createdBy', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('record_answer', sa.Column('editedBy', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('record_answer', sa.Column('createdBy', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('quiz', sa.Column('editedBy', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('quiz', sa.Column('createdBy', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('question', sa.Column('editedBy', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('question', sa.Column('createdBy', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('choice', sa.Column('editedBy', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('choice', sa.Column('createdBy', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
